FROM python:3.10-slim

WORKDIR /app

COPY ./test/requirements-test.txt .
RUN pip install --no-cache-dir -r requirements-test.txt

COPY ./test/data /app/data
COPY ./test/test_transcription.py .

CMD ["pytest", "-v", "test_transcription.py"] 